server:
  port: 6002
spring:
  application:
    name: information-pioneer-media-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.181.132:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 平台管理
        - id: media
          uri: lb://information-pioneer-media
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix= 1

